malla = {"Primer Semestre": ["Introducción a la Microeconomía",
                             "Cálculo I",
                             "Contabilidad I",
                             "Álgebra",
                             "Horizontes y Desafíos en la Gestión de Empresas",
                             "Examen de Comunicación Escrita",
                             "English Placement Test ALTE 3"],
         "Segundo Semestre": ["Introducción a la Macroenomía",
                             "Cálculo II",
                             "Contabilidad II",
                             "Comportamiento Humano en las Organizaciones",
                             "English Test",
                             "Electivo en otra Disciplina"],
         "Tercer Semestre": ["Probabilidad y Estadística",
                             "Análisis económico ",
                             "Experiencia Chilena",
                             "Cálculo III",
                             "OPR (Administración)",
                             "Teológico",
                             "Taller de computación I"],
         "Cuarto Semestre": ["Inferencia Estadística",
                             "MicroEconomía",
                             "Métodos de Optimización",
                             "Fundamentos de Dir. Empresa",
                             "Antropológico Ético",
                             "Taller de Computación II"],
         }